const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://jhj-developer.github.io/jeju-trip-2026/',runScripts:'outside-only'});
const w=dom.window;Object.defineProperty(w,'crypto',{value:webcrypto});w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.alert=()=>{};
for(const f of ['defaults.js','sync.js','app.js','notifications.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),dom.getInternalVMContext());
w.eval("active=data.days[0].id;render();openEditor(active,data.days[0].items[0].id)");
assert.equal(w.document.querySelector('#reminderInput').checked,true);
w.document.querySelector('#reminderInput').checked=false;w.document.querySelector('#editForm').dispatchEvent(new w.Event('submit',{cancelable:true}));
let saved=JSON.parse(w.localStorage.getItem('jejuTripPWA_v1'));assert.equal(saved.days[0].items[0].reminder,false);
w.eval('openEditor(active,data.days[0].items[0].id)');assert.equal(w.document.querySelector('#reminderInput').checked,false);w.document.querySelector('#editDialog').close();
w.eval('openDay(active)');w.document.querySelector('#dayDateInput').value='2026-10-26';w.document.querySelector('#dayForm').dispatchEvent(new w.Event('submit',{cancelable:true}));
saved=JSON.parse(w.localStorage.getItem('jejuTripPWA_v1'));assert.equal(saved.days[0].date,'2026-10-26');assert.equal(saved.days[0].items[0].reminder,false);
w.eval('openEditor(active)');assert.equal(w.document.querySelector('#reminderInput').checked,true);
assert.ok(w.document.querySelector('#pushSettings'));assert.ok(w.document.querySelector('#pushForm'));assert.ok(w.document.querySelector('#pushManage'));
console.log('PASS: app loads, default reminders enabled, opt-out saved and restored, new schedules default on, date changes preserve opt-out, family registration controls.');dom.window.close();
